name: catalogo_app_001
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  image_picker: ^1.0.7
  file_picker: ^10.1.2
  open_file: ^3.3.2
  pdf: ^3.10.7
  provider: ^6.1.1
  flutter_colorpicker: ^1.0.3
  qr_flutter: ^4.1.0
  path: ^1.8.3
  intl: ^0.20.2
  share_plus: ^10.1.4
  image: ^4.0.17
  photo_view: ^0.14.0 
  math_expressions: ^2.2.0
  webview_flutter: ^4.2.2
  permission_handler: ^11.0.0
  flutter_staggered_grid_view: ^0.7.0
  printing: ^5.11.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/

